sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - 6
  - 7

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli
  - npm install
  - ng build
script:
  - npm run ci
  
notifications:
  email:
    on_failure: change
    on_success: change
